[package]
name = "rust-postgres"
version = "0.1.0"
edition = "2021"

[dependencies]
faker_rand = "0.1.1"
rand = "0.8.5"
sqlx = { version = "0.8", features = [
    "runtime-tokio",
    "tls-native-tls",
    "postgres",
    "macros",
] }
tokio = { version = "1", features = ["full"] }
